/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export type ContractComponents = Awaited<ReturnType<typeof defineContractComponents>>;

export function defineContractComponents(world: World) {
  return {
    Challenge: (() => {
      return defineComponent(
        world,
        { namespace: RecsType.BigInt, address: RecsType.BigInt, is_available: RecsType.Boolean },
        {
          metadata: {
            name: "pistols64-Challenge",
            types: ["felt252","contractaddress","bool"],
            customTypes: [],
          },
        }
      );
    })(),
  };
}
