
// Generated by dojo-bindgen on Wed, 28 Aug 2024 13:03:23 +0000. Do not modify this file manually.
// Import the necessary types from the recs SDK
// generate again with `sozo build --typescript` 
import { Account, byteArray } from "starknet";
import { DojoProvider } from "@dojoengine/core";
import * as models from "./models.gen";

export type IWorld = Awaited<ReturnType<typeof setupWorld>>;

export async function setupWorld(provider: DojoProvider) {
    // System definitions for `pistols64-actions` contract
    function actions() {
        const contract_name = "actions";

        
        // Call the `world` system with the specified Account and calldata
        const world = async (props: { account: Account }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "world",
                        calldata: [],
                    },
                    "pistols64"
                );
            } catch (error) {
                console.error("Error executing spawn:", error);
                throw error;
            }
        };
            

    
        // Call the `create_challenge` system with the specified Account and calldata
        const create_challenge = async (props: { account: Account, duelist_name_a: bigint, duelist_name_b: bigint, message: bigint }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "create_challenge",
                        calldata: [props.duelist_name_a,
                props.duelist_name_b,
                props.message],
                    },
                    "pistols64"
                );
            } catch (error) {
                console.error("Error executing spawn:", error);
                throw error;
            }
        };
            

    
        // Call the `move` system with the specified Account and calldata
        const move = async (props: { account: Account, duel_id: bigint, round_number: number, duelist_name: bigint, moves: RecsType.NumberArray }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "move",
                        calldata: [props.duel_id,
                props.round_number,
                props.duelist_name,
                ...props.moves],
                    },
                    "pistols64"
                );
            } catch (error) {
                console.error("Error executing spawn:", error);
                throw error;
            }
        };
            

    
        // Call the `live_long` system with the specified Account and calldata
        const live_long = async (props: { account: Account }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "live_long",
                        calldata: [],
                    },
                    "pistols64"
                );
            } catch (error) {
                console.error("Error executing spawn:", error);
                throw error;
            }
        };
            

        return {
            world, create_challenge, move, live_long
        };
    }

    // System definitions for `pistols64-rng` contract
    function rng() {
        const contract_name = "rng";

        
        // Call the `reseed` system with the specified Account and calldata
        const reseed = async (props: { account: Account, seed: bigint, salt: bigint }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "reseed",
                        calldata: [props.seed,
                props.salt],
                    },
                    "pistols64"
                );
            } catch (error) {
                console.error("Error executing spawn:", error);
                throw error;
            }
        };
            

    
        // Call the `world` system with the specified Account and calldata
        const world = async (props: { account: Account }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "world",
                        calldata: [],
                    },
                    "pistols64"
                );
            } catch (error) {
                console.error("Error executing spawn:", error);
                throw error;
            }
        };
            

        return {
            reseed, world
        };
    }

    return {
        actions: actions(),
        rng: rng()
    };
}
